In [58]:
import pandas as pd
import numpy as np

In [59]:
data = pd.read_csv("/hackathon_dataset.csv")

In [60]:
data.head()

,Age,Gender,Vehicle_Age,Annual_Mileage,Vehicle_Power_HP,Years_Driving,Traffic_Violations,Number_of_Claims,Total_Claim_Amount,Policy_Duration_Years,...,Collision_Rate_Region,Policy_Payment_Frequency,Automatic_Payment_Flag,Failed_Payment_Count,Customer_LTV_Est,Cross_Sell_Product_Count,Loyalty_Discount_Applied,Distance_To_Work_km,Work_Mode,Tech_Adoption_Score
0,49.0,Male,3.7,11920.0,60.0,36.0,1,1,2732.59,9.08,...,5.1,Quarterly,1,0,15116.83,2,1,10.7,Onsite,58
1,33.0,Female,1.1,11119.0,159.0,16.0,0,0,0.00,0.53,...,5.6,Quarterly,0,2,2069.74,1,1,15.3,Onsite,48
2,54.0,Female,14.4,8389.0,133.0,37.0,0,0,0.00,5.19,...,6.2,Monthly,0,0,9102.96,0,1,NaN,Remote,4
3,56.0,Female,1.4,11068.0,127.0,42.0,2,0,0.00,9.59,...,3.3,Monthly,0,0,20915.65,0,0,5.9,Hybrid,68
4,22.0,Male,1.9,12199.0,134.0,4.0,0,0,0.00,7.21,...,4.6,Monthly,0,0,29088.31,3,0,6.4,Hybrid,57

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 66 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            50000 non-null  float64
 1   Gender                         50000 non-null  object
 2   Vehicle_Age                    50000 non-null  float64
 3   Annual_Mileage                 50000 non-null  float64
 4   Vehicle_Power_HP               50000 non-null  float64
 5   Years_Driving                  50000 non-null  float64
 6   Traffic_Violations             50000 non-null  int64
 7   Number_of_Claims               50000 non-null  int64
 8   Total_Claim_Amount             50000 non-null  float64
 9   Policy_Duration_Years          50000 non-null  float64
 10  Premium_Cost                   50000 non-null  float64
 11  Marital_Status                 50000 non-null  object
 12  Credit_Score                   50000 non-null  float64
 13  Telematics_Score               50000 non-null  float64
 14  Policy_Type                    50000 non-null  object
 15  Vehicle_Type                   50000 non-null  object
 16  Safety_Features_Count          50000 non-null  int64
 17  Annual_Coverage_Limit          50000 non-null  int64
 18  Deductible_Amount              50000 non-null  int64
 19  Multi_Policy_Discount          50000 non-null  int64
 20  Time_Since_Last_Claim          50000 non-null  float64
 21  Claims_Severity                7809 non-null   object
 22  Policy_Start_Month             50000 non-null  int64
 23  Usage_Type                     50000 non-null  object
 24  Garage_Location                50000 non-null  object
 25  Annual_Income                  50000 non-null  float64
 26  Preferred_Channel              50000 non-null  object
 27  Price_Sensitivity_Score        50000 non-null  float64
 28  Campaign_Response_Flag         50000 non-null  int64
 29  Loyalty_Tenure_Years           50000 non-null  float64
 30  Payment_Method                 50000 non-null  object
 31  Past_Due_Payments              50000 non-null  int64
 32  Risk_Score                     50000 non-null  float64
 33  Predicted_Claim_Probability    50000 non-null  float64
 34  Claim_Next_Year_Flag           50000 non-null  int64
 35  Product_Purchased              50000 non-null  object
 36  Family_Size                    50000 non-null  int64
 37  Number_of_Dependents           50000 non-null  int64
 38  Education_Level                50000 non-null  object
 39  Occupation_Type                50000 non-null  object
 40  Home_Ownership                 50000 non-null  object
 41  Smartphone_Owner_Flag          50000 non-null  int64
 42  Website_Login_Freq_Month       50000 non-null  int64
 43  App_Usage_Freq_Month           50000 non-null  int64
 44  Email_Open_Rate                50000 non-null  float64
 45  Click_Through_Rate             50000 non-null  float64
 46  Discount_Applied_Last_Renewal  50000 non-null  int64
 47  Quote_Comparison_Count         50000 non-null  int64
 48  Agent_Interaction_Count        50000 non-null  int64
 49  NPS_Score                      50000 non-null  float64
 50  Claims_Satisfaction_Score      7809 non-null   float64
 51  Hard_Brake_Events              50000 non-null  int64
 52  Night_Driving_Pct              50000 non-null  float64
 53  Speeding_Events                50000 non-null  int64
 54  Phone_Usage_While_Driving      50000 non-null  int64
 55  Weather_Severity_Index         50000 non-null  float64
 56  Collision_Rate_Region          50000 non-null  float64
 57  Policy_Payment_Frequency       50000 non-null  object
 58  Automatic_Payment_Flag         50000 non-null  int64
 59  Failed_Payment_Count           50000 non-null  int64
 60  Customer_LTV_Est               50000 non-null  float64
 61  Cross_Sell_Product_Count       50000 non-null  int64
 62  Loyalty_Discount_Applied       50000 non-null  int64
 63  Distance_To_Work_km            30065 non-null  float64
 64  Work_Mode                      50000 non-null  object
 65  Tech_Adoption_Score            50000 non-null  int64
dtypes: float64(25), int64(26), object(15)
memory usage: 25.2+ MB

In [62]:
data['Claims_Severity'].value_counts()

Claims_Severity
Moderate    4214
Minor       3221
Severe       374
Name: count, dtype: int64

In [63]:
data['Gender'].value_counts()

Gender
Male      29930
Female    20070
Name: count, dtype: int64

In [64]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [31]:
#Gender OneHot
#Marital_Status OneHot
#Policy_Type OneHotEncoder
#Vehicle_Type OneHot
#Claims_Severity Ordinal
#Usage_Type OneHotEncoder
#Garage_Location OneHotEncoder
#Preferred_Channel OneHotEncoder
#Payment_Method OneHotEncoder
#Product_Purchased OrdinalEncoder
#Education_Level OrdinalEncoder
#Occupation_Type OneHotEncoder
#Home_Ownership OrdinalEncoder
#Policy_Payment_Frequency OrdinalEncoder
#Work_Mode OneHotEncoder

In [65]:
from sklearn.compose import ColumnTransformer

In [66]:
# Define the custom order for each categorical feature
Claims_Severity = ['Minor', 'Moderate', 'Severe', 'NAN']
# Claims_Severity_with_nan = [x for x in Claims_Severity if pd.notna(x)] + [np.nan]  # Place NaN at the end

In [67]:
# Claims_Severity= ['Moderate', 'Minor', 'Severe']
Product_Purchased = ['Comprehensive Coverage', 'Liability Only', 'Collision Coverage']
Education_Level = ['Bachelor', 'Master', 'Doctorate', 'High School']
Home_Ownership = ['Mortgaged', 'Owned', 'Rented']
Policy_Payment_Frequency = ['Monthly', 'Quarterly', 'Annual']

In [68]:
col_tr = ColumnTransformer([
    ('ohe', OneHotEncoder(handle_unknown='ignore', categories=[
        data['Gender'].unique(),
        data['Marital_Status'].unique(),
        data['Policy_Type'].unique(),
        data['Vehicle_Type'].unique(),
        Claims_Severity,  # Handle NaN correctly
        data['Usage_Type'].unique(),
        data['Garage_Location'].unique(),
        data['Preferred_Channel'].unique(),
        data['Payment_Method'].unique(),
        data['Product_Purchased'].unique(),
        data['Education_Level'].unique(),
        data['Occupation_Type'].unique(),
        data['Home_Ownership'].unique(),
        data['Policy_Payment_Frequency'].unique(),
        data['Work_Mode'].unique()])
    ,['Gender','Marital_Status','Policy_Type', 'Vehicle_Type', 'Claims_Severity', 'Usage_Type', 'Garage_Location', 'Preferred_Channel', 'Payment_Method', 'Product_Purchased', 'Education_Level', 'Occupation_Type', 'Home_Ownership', 'Policy_Payment_Frequency', 'Work_Mode']),

    ('ordinal', OrdinalEncoder(categories=[
        Claims_Severity_with_nan,  # Handle NaN correctly
        Product_Purchased,
        Education_Level,
        Home_Ownership,
        Policy_Payment_Frequency
    ]), ['Claims_Severity', 'Product_Purchased', 'Education_Level', 'Home_Ownership', 'Policy_Payment_Frequency'])
], remainder='passthrough')

In [70]:

transform_data = col_tr.fit_transform(data)

In [72]:
len(transform_data[0])

111